### ISSUE TITLE
Rename components

### ISSUE THREAD

**Issue by elaman** [bayel-bakytov/shawarma-builder#3]
Rename these components:

- [x] **Ingredients** to **Ingredient** _(without 's')_
- [x] **ShawarmaIngredients** to **Ingredients**
- [x] **IngredientsControls** to **ShawarmaControls**
- [x] **IngredientControl** to ** ShawarmaControl**

**Comment by bayel-bakytov** [comment]
@elaman Agai i renamed the components.
