### ISSUE TITLE
Randomize rotation

### ISSUE THREAD

**Issue by elaman** [bayel-bakytov/shawarma-builder#7]
Something like this
`transform: 'rotate(' + Math.random() * 360 + ')'`
should be here:
https://github.com/bayel-bakytov/shawarma-builder/blob/da5e511422f14415e465de4d00850f9f3495a911/src/components/ShawarmaBuilder/Ingredients/Ingredient/Ingredient.js#L48

**Comment by bayel-bakytov** [comment]
@elaman  Agai 
I added a random rotation to the ingredients. And it works.Thanks Agai.
